name = "HSL"
uuid = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
version = "0.2.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
METIS_jll = "d00139f3-1899-568f-a2f0-47f597d42d70"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinaryProvider = "^0.5"
METIS_jll = "4.0.3"
OpenBLAS32_jll = "0.3.9"
julia = "^1.3.0"
